### ISSUE TITLE
@region('') doesn't work

### ISSUE THREAD

**Issue by peterbrinck** [agentejo/copilot#1]
When adding a region to a page from the editor in Cockpit, the page just outputs the code, `@region('RegionName')`

**Comment by aheinze** [comment]
should be fixed with the following commit: https://github.com/COCOPi/cocopi-kickstart/commit/e8884f541c34c77597de11244bbf1510ee6e6d57

**Comment by peterbrinck** [comment]
`@region('RegionName)` still doesn't work, regardless of what the config says
