### ISSUE TITLE
Docs: Example of field addon

### ISSUE THREAD

**Issue by amdad** [agentejo/copilot#12]
I saw how you've added color picker to core. But how it would be to add the same color picker (or any other dummy example) to `modules/addons`? To have separate package independent from updates?

**Comment by aheinze** [comment]
take a look here: https://github.com/COCOPi/cocopi-kickstart/blob/master/cockpit/modules/addons/Copilot/admin.php#L98

**Comment by amdad** [comment]
Thanks! But this method allow me to extend default form types list? 

Extend this? modules/core/Cockpit/assets/components.js

**Comment by aheinze** [comment]
components.js are all compiled core components of cockpit, the method above dynamiclly loads and compiles webcomponents based on riotjs

**Comment by amdad** [comment]
Does, name have any special meaning? I see `field-`  prefix. This is required?

**Comment by aheinze** [comment]
yes
