### ISSUE TITLE
Collection entries can't be sorted

### ISSUE THREAD

**Issue by peterbrinck** [agentejo/copilot#17]
When creating a collection, and enabling Sortable Entries, you should be able to drag the entries to change the order. But that doesn't work. I can't drag them. When I do, they disappear and I have to click a few times before it comes back.

https://forum.cocopi.co/topic/5/collection-entries-can-t-be-sorted/

**Comment by aheinze** [comment]
should be fixed now, with the following commit: https://github.com/COCOPi/cocopi-kickstart/commit/28bed4eaf361d87928094a5f28569fe3a27a6d55

**Comment by peterbrinck** [comment]
Yes, it is fixed
