### ISSUE TITLE
CoCo 404 on adding new page (only windows localhost)

### ISSUE THREAD

**Issue by amdad** [agentejo/copilot#2]
In localhost (windows wamp) environment, when adding new page to copilot through cockpit, HTML or Markdown. It throws 404. On regular Linux server problem didn't appear.

**Comment by aheinze** [comment]
I'll look into that

**Comment by russellfeeed** [comment]
Same here. Using XAMPP I get a 404 and am stuck in a redirect to
cocopi/cockpit/coco/page/content//my-new-page/index.html

**Comment by aheinze** [comment]
I need to setup a windows box to test this...hope to get this fixed soon

**Comment by amdad** [comment]
Your commit solved broken Blog (path problem) on windows. But on cockpit/copilot I still have 404 error when try to create new page.

`http://localhost/c/cockpit/copilot/page/content/new-page/index.html` still give me 404

**Comment by amdad** [comment]
When create collection or region and save it, it goes OK. When try to resave it again it throw red **Saving failed.** notification. On linux (server) problem doesn't exist.
